name: 'Publish FTP action'
description: 'This action publish your repo in a (S)FTP server'
inputs:
  host:
    description: '(S)FTP host'
    required: true
  username:
    description: '(S)FTP user'
    required: true
  password:
    description: '(S)FTP password'
    required: false
  folder:
    description: 'Folder for chdir'
    required: false
  port:
    description: '(S)FTP port'
    required: false
  type:
    description: 'FTP or SFTP protocol'
    required: false
output:
  exit-status:
    description: 'Exit status of the (S)FTP transfer'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.folder }}
    - ${{ inputs.port }}
    - ${{ inputs.type }}
