name: 'Publish FTP action'
description: 'This action publish your repo in a (S)FTP server'
inputs:
  host:
    description: '(S)FTP host'
    required: true
  username:
    description: '(S)FTP user'
    required: true
  password:
    description: '(S)FTP password'
    required: false
  ssh_key:
    description: 'SSH key used for the connection (passphrase is not supported)'
    required: false
  remote_folder:
    description: 'Remote folder to chdir'
    required: false
  repo_folder:
    description: 'Repository folder to transfer'
    required: false
  port:
    description: '(S)FTP port'
    required: false
  type:
    description: 'FTP or SFTP protocol'
    required: false
  put_github_sha:
    description: 'Transfer file named with the pushed GitHub SHA'
    required: false
output:
  exit-status:
    description: 'Exit status of the (S)FTP transfer'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.ssh_key }}
    - ${{ inputs.folder }}
    - ${{ inputs.port }}
    - ${{ inputs.type }}
